services:
    web:
        image: nginx:latest
        container_name: '${APP_NAME}-nginx'
        ports:
            - '${APP_PORT}:80'
        volumes:
            - './src:/var/www/html'
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
    
    php-fpm:
        build: './docker/php/'
        container_name: '${APP_NAME}-php-fpm'
        volumes:
            - './src:/var/www/html'
    
    mariadb:
        image: mariadb:latest
        working_dir: /var/www/html
        container_name: '${APP_NAME}-db'
        restart: always
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASS}'
            MYSQL_DATABASE: '${MYSQL_DB}'
        volumes:
            - ./docker/db_data:/var/lib/mysql
            - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
            - './src/${APP_NAME}:/var/www/html'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: '${APP_NAME}-myadmin'
        links:
            - mariadb
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - '${MYADMIN_PORT}:80'

    mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: '${APP_NAME}-mailhog'
        ports:
            - '${MAILHOG_PORT}:8025'

    elasticsearch:
        image: elasticsearch:7.17.4
        container_name: '${APP_NAME}-elasticsearch'
        environment:
            - "discovery.type=single-node"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - '${ELASTIC_PORT1}:9200'
            - '${ELASTIC_PORT2}:9300'
        volumes:
            - ./docker/data/elastic:/usr/share/elasticsearch/data